language: python
sudo: false
python:
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_b28ee498f040_key -iv $encrypted_b28ee498f040_iv
  -in .onshapepy.enc -out $HOME/.onshapepy -d
- export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
install:
- pip install pipenv
- pipenv install --dev
- gem install html-proofer
script:
- pipenv run pytest --cov=./
- cd docs
- pipenv run make html
- pipenv run make doctest
- htmlproofer build/html --allow_hash_href --file_ignore "build/html/search.html"
- cd ..
after_success:
- pipenv run codecov
deploy:
- provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  on:
    tags: true
  distributions: sdist
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: docs/build/html
  target-branch: gh-pages
  on:
    tags: true
